export default {
  FACULTY: "FACULTY",
  FACULTY_STUDY_FORMS: {
    FMTI: "FACULTY/STUDY_FORMS/FMTI",
    BIO_CH: "FACULTY/STUDY_FORMS/BIO_CH",
    GEO: "FACULTY/STUDY_FORMS/GEOGRAFY",
    PHILO: "FACULTY/STUDY_FORMS/PHILOLOGY",
    PED: "FACULTY/STUDY_FORMS/PEDAGODY"
  },
  FACULTY_GENERAL_INFO: {
    FMTI: "FACULTY/GENERAL_INFO/FMTI",
    BIO_CH: "FACULTY/GENERAL_INFO/BIO_CH",
    GEO: "FACULTY/GENERAL_INFO/GEOGRAFY",
    PHILO: "FACULTY/GENERAL_INFO/PHILOLOGY",
    PED: "FACULTY/GENERAL_INFO/PEDAGODY"
  },
  HELP: "HELP",
  ADMITTANCE: "ADMITTANCE",
  GET_STARTED: "GET_STARTED",
  STUDY_FORM: {
    BACHELOR: "BACHELOR",
    MASTER: "MASTER",
    PHD: "PHD"
  }
}